twter/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('twts/', include('twts.urls')),
    path('admin/', admin.site.urls),
]

twts/urls.py
from django.urls import path

from . import views

app_name = 'twts'
urlpatterns = [
    #/twts/posttwt
    path('postwt/<int:posteroftwt_id>/', views.posttwt, name="posttwt"),
    #/twts/authenticate/
    path('authenticate', views.authenticate, name='authenticate'),
    # /twts/indexnewuser/
    path('indexnewuser', views.indexnewuser, name='indexnewuser'),
    # ex: /twts/
    path('', views.home, name='home'),
    # ex: /twts/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /twts/5/vote/
    path('<int:twt_id>/vote/', views.vote, name='vote'),
    # ex /twts/reply/6/
    path('reply/<int:twt_id>/', views.replytotwt, name='replytotwt')
]

twts/models.py
"""
DJANGO 3.0.3
PYTHON 3.7.0
BOOTSTRAP 3.4.1
"""




import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class TwtPoster(models.Model):
    # this is a de facto user model, which has the attributes of email and password.
    twtposter_text = models.CharField('twtposter username/email', max_length=200, default="emptyuser")
    twtposter_password = models.CharField('twtposter password', max_length=200, default="emptypassword")

    def __str__(self):
        return self.twtposter_text


class Twt(models.Model):
    twt_text = models.CharField('twt text', max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now())
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    twtposter = models.ForeignKey(TwtPoster,on_delete=models.CASCADE) # this connects every individual twt to a TwtPoster user

    def __str__(self):
        return self.twt_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Reply(models.Model):
    twt = models.ForeignKey(Twt,on_delete=models.CASCADE) # related to a twt
    reply_poster = models.ForeignKey(TwtPoster,on_delete=models.CASCADE) # related to twtposter
    reply_text = models.CharField('twt text', max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now())

    def __str__(self):
        return self.reply_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



"""class Twt(models.Model):
    twt_text = models.CharField('twt text', max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now())
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)
    #twtposter = models.ForeignKey(TwtPoster,on_delete=models.CASCADE)  this connects every individual twt to a TwtPoster user
    twtposter = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.twt_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)"""

twts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Twt, TwtPoster, Reply



def home(request):
    # view sends the request to the home.html template; for sign ups and logins.
    return render(request, 'twts/home.html')

def indexnewuser(request):
    # builds the new TwtPoster object from the sign up form data in request and updates the database
    newUser = TwtPoster(twtposter_text=request.POST['email'],twtposter_password=request.POST['psw'])
    newUser.save()
    # subsequently shows the 5 most recent twts via the index template
    latest_twt_list = Twt.objects.order_by('-pub_date')[:5]
    context = {'latest_twt_list': latest_twt_list, 'user': newUser}
    return render(request, 'twts/index.html', context)


class DetailView(generic.DetailView):
    model = Twt
    template_name = 'twts/detail.html'



def posttwt(request,posteroftwt_id):
    # posting a new twt to the database based on the index.html template form provided
    newTwt = Twt(twt_text=request.POST['newesttwt'],twtposter=get_object_or_404(TwtPoster,id=posteroftwt_id))
    newTwt.save()


    # inefficient implementation below, can functionalize this context builiding later
    latest_twt_list = Twt.objects.order_by('-pub_date')[:5]
    context = {'latest_twt_list': latest_twt_list, 'user': newTwt.twtposter  }
    return render(request, 'twts/index.html', context)


def vote(request, twt_id):
    # This adds a like or dislike to a given twt, and returns a different TwtPoster to theindex.html template.
    twt = get_object_or_404(Twt, pk=twt_id)
    # when both like and dislike options are null (and there's only the crsf_token in the request.POST dictionary), the user didn't choose a choice.
    if  len(request.POST) == 1:
        # Redisplay the twt voting form.
        return render(request, 'twts/detail.html', {
            'twt': twt,
            'error_message': "You didn't select an option.",
        })
    elif ('like' in request.POST.keys()): # when the like can be accessed in the request.POST dictionary, the user voted to like the twt.
        twt.likes += 1
    else:
        twt.dislikes += 1

    twt.save()

    # inefficient implementation below, can functionalize this context builiding later
    latest_twt_list = Twt.objects.order_by('-pub_date')[:5]
    context = {'latest_twt_list': latest_twt_list, 'user': twt.twtposter  } # passing in a new user TwtPoster object for the twt just selected for a vote
    # this is non - ideal, but I thought it would be interesting switching accounts.
    return render(request, 'twts/index.html', context)




def replytotwt(request, twt_id):
    # builds a new reply to the twt, protecting anonymity on the detail.html template
    reply = Reply(reply_text=request.POST['replytext'],twt=get_object_or_404(Twt,id=twt_id),reply_poster=get_object_or_404(TwtPoster,id=1))
    reply.save()

    # inefficient implementation below, can functionalize this context builiding later
    latest_twt_list = Twt.objects.order_by('-pub_date')[:5]
    context = {'latest_twt_list': latest_twt_list, 'user': reply.reply_poster  } # passing in a new user TwtPoster object for the twt just selected for a vote
    # this is non - ideal, but I thought it would be interesting switching accounts.
    return render(request, 'twts/index.html', context)





def authenticate(request):
    # verifies the user's password is correct from the home.html template form
    user = get_object_or_404(TwtPoster,twtposter_text=request.POST['uname']) # TwtPoster based on supplied email in the login form
    try:
        if user.twtposter_password == request.POST['psw']: # password is correct
            # inefficient implementation below, can functionalize this context builiding later
            latest_twt_list = Twt.objects.order_by('-pub_date')[:5]
            context = {'latest_twt_list': latest_twt_list, 'user': user} # passing in the current user TwtPoster object
            return render(request, 'twts/index.html', context)
        else:
            return render(request, 'twts/detail.html', {
                'twt': user,
                'error_message': "No such user",
                })
    except(KeyError,TwtPoster.DoesNotExist):
        return render(request, 'twts/detail.html', {
            'twt': user,
            'error_message': "No such user.",
        })




# Create your views here.

twts/templates/twts/detail.html
<h1>Twt:      {{ twt.twt_text }}</h1>
<h3>Replies!</h3>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} <!-- shows error messages for user authentication defects; needs improvement -->

{% if twt.reply_set.count > 0 %}  <!-- only formulates when there are available reply objects-->
  {% for reply in twt.reply_set.all %} <!-- loops through the reply objects related by foreign key in a many to one relationship -->
    <h3>{{reply.reply_text}}</h3>
  {% endfor %}
{% endif %}

<form action="{% url 'twts:replytotwt' twt.id %}" method="post">
  {% csrf_token %}
  <label for="replytext"><b>Reply!</b></label>
  <input type="text" placeholder="Enter a reply" name="replytext" required> <!-- form to post a new reply -->

  <input type="submit" value="Reply"> <!-- replying to the twt -->
</form>


<form action="{% url 'twts:vote' twt.id %}" method="post">
  {% csrf_token %}
    <input type="radio" name="like" value=1>
    <label>Like!</label>
    <input type="radio" name="dislike" value=1>
    <label>Dislike!</label>

<input type="submit" value="Vote"> <!-- two options passed into the request.POST object-->
</form>

twts/templates/twts/home.html
<!DOCTYPE html>
<html>
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

/* from W3 Schools https://www.w3schools.com/howto/howto_css_login_form.asp */

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

/* Add a background color when the inputs get focus */
input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Set a style for all buttons */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
  padding: 14px 20px;
  background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
  padding: 16px;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color: #474e5d;
  padding-top: 50px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* Style the horizontal ruler */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

/* The Close Button (x) */
.close {
  position: absolute;
  right: 35px;
  top: 15px;
  font-size: 40px;
  font-weight: bold;
  color: #f1f1f1;
}

.close:hover,
.close:focus {
  color: #f44336;
  cursor: pointer;
}

/* Clear floats */
.clearfix::after {
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .signupbtn {
     width: 100%;
  }
}
</style>
<body>

<h2>SignUp/Login for Twts!</h2>

<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Sign Up</button>

<div id="id01" class="modal">
  <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
  <form class="modal-content" action="/twts/indexnewuser" method="post">
    {% csrf_token %} <!-- needed for django security reasons -->
    <div class="container">
      <h1>Sign Up</h1>
      <p>Please fill in this form to create an account.</p>
      <hr>
      <label for="email"><b>Email</b></label>
      <input type="text" placeholder="Enter Email" name="email" required>

      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>

      <label for="psw-repeat"><b>Repeat Password</b></label>
      <input type="password" placeholder="Repeat Password" name="psw-repeat" required>


      <div class="clearfix">
        <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
        <button type="submit" class="signupbtn">Sign Up</button>
      </div>
    </div>
  </form>
</div>



<button onclick="document.getElementById('id02').style.display='block'" style="width:auto;">Login</button>

<div id="id02" class="modal">

  <form class="modal-content animate" action="/twts/authenticate" method="post">
    {% csrf_token %} <!-- needed for django security reasons -->
    <div class="imgcontainer">
      <span onclick="document.getElementById('id02').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="static/twts/twterlogo.png" alt="Avatar" class="avatar">
    </div>

    <div class="container">
      <label for="uname"><b>Email</b></label>
      <input type="text" placeholder="Enter email" name="uname" required>

      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>

      <button type="submit">Login</button>
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id02').style.display='none'" class="cancelbtn">Cancel</button>
    </div>
  </form>
</div>

<script>
// Get the modal for sign up only
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>

</body>
</html>

twts/templates/twts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Twts!</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>



<div class="container">
  <h2> Recent Twts! (Those in red are yours!)</h2>
  <table class="table">

    <thead> <!-- categories in the header -->
      <tr>

        <th>Username/Email</th>
        <th>Twt</th>
        <th>Likes</th>
        <th>Dislikes</th>

      </tr>
    </thead>

    <tbody>

      {% for twt in latest_twt_list %}
        <!-- highlights red if the viewing TwtPoster previously posted the twt -->
        <tr {% if user.twtposter_text == twt.twtposter.twtposter_text %}style="background-color:Tomato;"{% endif %}>

          <th>{{ twt.twtposter.twtposter_text }}</th> <!-- shows the username -->
          <th>{{ twt.twt_text }}</th> <!-- shows the twt's content -->
          <th><a href="{% url 'twts:detail' twt.id %}"><button>{{ twt.likes }}</button></a></th> <!-- shows the number of likes and allows for liking-->
          <th><a href="{% url 'twts:detail' twt.id %}"><button>{{ twt.dislikes }}</button></a></th> <!-- shows the number of dislikes and allows for disliking-->

        </tr>
      {% endfor %}

    </tbody>
  </table>

  <form action={% url 'twts:posttwt' user.id %} method="post">

    {% csrf_token %}
    <label for="newesttwt"><b>Twt!</b></label>
    <input type="text" placeholder="Enter a twt" name="newesttwt" required> <!-- form to post a new twt -->

  </form>

</div>


<!-- TEST/BASE CODE; DISREGARD
{% if latest_twt_list %}
    <ul>
    {% for twt in latest_twt_list %}
        <li><a href="{% url 'twts:detail' twt.id %}">{{ twt.twt_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No twts are available.</p>
{% endif %}
-->

</body>
</html>

twts/templates/twts/results.html
<h1>{{ twt.twt_text }}</h1>

<ul>
{% for twtposter in twt.twtposter_set.all %}
    <li>{{ twtposter.twtposter_text }} -- {{ twtposter.votes }} vote{{ twtposter.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'twts:detail' twt.id %}">Vote again?</a>